### ISSUE TITLE
etouq and file compilation

### ISSUE THREAD

**Issue by lispm** [terminal625/utility#1]
The ETOUQ macro is used in a few places in your code. It's purpose seems to be to run some code at macro expansion time (-> compile time).

If we compile a file which has usage of that macro, this means that code which is run my this macro needs to be available at compile time. For portable code there are some traps to fall into. For example in you code there is a DEFCONSTANT +fixnum-bits+ . It seems to be undefined in standard Common Lisp whether the defconstant variable will have a value at compile-time. Thus in some CL implementations the next form (the definition of PRINT-BITS) will fail to compile, since it uses the compile-time value of +fixnum-bits+. Examples where this fails are CLISP and LispWorks.

Thus the DEFCONSTANT form needs an (eval-when :compile-toplevel :load-toplevel :execute) ...)  around it - so that it is executed at compile time, too.

There is the possibility that similar effects are in your code, which work in SBCL, because it may evaluate some stuff in the compile-time environment.

**Comment by gregcman** [comment]
I cannot thank you enough for taking time to give me a detailed, actionable explanation. Turns out there were and probably still are multiple instances where I relied on non-portable SBCL specific details for compile times, like [here](https://github.com/terminal625/sucle/blob/master/application/subsystems/sandbox/block-meshing.lisp), which now, thanks to you, can work with CCL [and probably others]. 
> Thus the DEFCONSTANT form needs an (eval-when :compile-toplevel :load-toplevel :execute) ...)

This [commit](https://github.com/terminal625/utility/commit/d7c00d0eec4a4fca925fd6a3a256be0b8a4d0dcf) does what you described for `DEFCONSTANT`. It now works with CLISP, but I was unable to test in on LispWorks. 

Do you have any tips on how to write portable CL code? My guess is that there need to be tests on multiple implementations every so often.
